cmake_minimum_required(VERSION 3.25)

if(package_windows)
    if(NOT package_arch EQUAL 8)
        message(FATAL_ERROR "Windows packaging requires a 64-bit build.")
    endif()
    set(platform "windows-x64")
    set(extension "zip")
elseif(package_system STREQUAL "Linux")
    if(package_processor MATCHES "^(x86_64|AMD64|amd64)$")
        set(platform "linux-x64")
    elseif(package_processor MATCHES "^(aarch64|arm64)$")
        set(platform "linux-arm64")
    else()
        message(FATAL_ERROR "Unsupported Linux architecture: ${package_processor}")
    endif()
    set(extension "tar.gz")
else()
    message(FATAL_ERROR "Packaging supports Windows and Linux.")
endif()
if(NOT package_config STREQUAL "Release")
    message(FATAL_ERROR "Package with the Release configuration.")
endif()

string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 nonce)
set(folder "${package_name}-${platform}")
set(stage_parent "${package_staging}/${stamp}-${nonce}")
set(stage "${stage_parent}/${folder}")
file(MAKE_DIRECTORY "${stage}/assets/${package_asset_folder}" "${package_output}")
file(COPY "${package_executable}" DESTINATION "${stage}")
file(COPY "${package_assets}/" DESTINATION "${stage}/assets/${package_asset_folder}")
set(search_dirs "${stage}")
foreach(dependency IN LISTS package_runtime package_dlls)
    file(COPY "${dependency}" DESTINATION "${stage}")
    get_filename_component(directory "${dependency}" DIRECTORY)
    list(APPEND search_dirs "${directory}")
endforeach()
get_filename_component(executable_name "${package_executable}" NAME)
if(package_windows)
    file(GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${stage}/${executable_name}"
        DIRECTORIES ${search_dirs}
        RESOLVED_DEPENDENCIES_VAR resolved
        UNRESOLVED_DEPENDENCIES_VAR unresolved
        PRE_EXCLUDE_REGEXES "[Aa][Pp][Ii]-[Mm][Ss]-.*" "[Ee][Xx][Tt]-[Mm][Ss]-.*"
        POST_EXCLUDE_REGEXES ".*[/\\][Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\][Ss][Yy][Ss][Tt][Ee][Mm]32[/\\].*")
else()
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM linux+elf)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${package_objdump}")
    file(GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${stage}/${executable_name}"
        RESOLVED_DEPENDENCIES_VAR resolved
        UNRESOLVED_DEPENDENCIES_VAR unresolved)
endif()
if(unresolved)
    message(FATAL_ERROR "Cannot package unresolved runtime dependencies: ${unresolved}")
endif()
if(package_windows)
    foreach(dependency IN LISTS resolved)
        get_filename_component(directory "${dependency}" DIRECTORY)
        if(NOT directory STREQUAL stage)
            file(COPY "${dependency}" DESTINATION "${stage}")
        endif()
    endforeach()
    set(archive_arguments cf "${package_output}/${folder}.${extension}" --format=zip "${folder}")
else()
    file(WRITE "${stage}/runtime-dependencies.txt"
        "Native Linux build. These shared libraries must be installed on the destination system.\nUse a compatible distribution and architecture. Graphics and audio drivers are supplied by the system.\n\n")
    foreach(dependency IN LISTS resolved)
        get_filename_component(library "${dependency}" NAME)
        file(APPEND "${stage}/runtime-dependencies.txt" "${library}\n")
    endforeach()
    set(archive_arguments czf "${package_output}/${folder}.${extension}" --format=gnutar "${folder}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar ${archive_arguments}
    WORKING_DIRECTORY "${stage_parent}"
    COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Package: ${package_output}/${folder}.${extension}")
message(STATUS "Unpacked files: ${stage}")
